name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          cache-environment: true
      - name: Lint
        shell: micromamba-shell {0}
        run: ruff check .
      - name: Test
        shell: micromamba-shell {0}
        run: pytest

